server:
  port: <Port>
  servlet:
    session:
      tracking-modes: cookie
      timeout: 12h
      cookie:
        name: KKUTU-WEB-SESSION

spring:
  thymeleaf:
    cache: true
  messages:
    basename: locale/message
    encoding: UTF-8
    fallback-to-system-locale: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://<Host>:<Port>/<Database>
    username: <Username>
    password: <Password>
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: <Host>
    port: <Port>
